# -*- coding: utf-8 -*-
"""Docking_GD_Parallel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P4GssDPNRBrGwGPIuuTlIdHmC0J2TjxJ
"""

import os
import sys

from docking_gd_parallel import *

'''if len(sys.argv) != 5:
    print('Wrong input parameters\n\n')
    print(len(sys.argv))
    exit()

pdb_path = sys.argv[1]
res_path = sys.argv[2]
OUT = sys.argv[3]
weight_file = sys.argv[4]'''



#pdb_path = '/home/esdft/DeepRLP/data/3HE4_AB.pdb'
pdb_path = '/home/esdft/DeepRLP/data/3HE4_rotated1.pdb'
#pdb_path = '/home/esdft/Desktop/3HE4A_3HE4B.pdb'
res_path = '/home/esdft/DeepRLP/data/3HE4A_3HE4B.rr'
OUT = '/home/esdft/Downloads/'
weight_file = '/home/esdft/DeepRLP/data/talaris2013.wts'



pose = pyrosetta.pose_from_pdb(pdb_path)
    
add_cons_to_pose(pose, res_path).apply(pose)

scorefxn = ScoreFunction()
#scorefxn.add_weights_from_file(weight_file)
scorefxn.set_weight(atom_pair_constraint, 1)


print(scorefxn.show(pose))






















#do_dock(pdb_path, res_path, OUT, weight_file)
